apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-go-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-go
  template:
    metadata:
      labels:
        app: hello-go
    spec:
      containers:
        - name: hello-go-container
          image: localhost/hello-go-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          # Liveness Probe
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
          # Readiness Probe
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
