apiVersion: v1
kind: Service
metadata:
  name: hello-go-service
spec:
  type: LoadBalancer
  selector:
    app: hello-go
  ports:
    - protocol: TCP
      port: 8082        # Port accessible on your LAN
      targetPort: 8080  # Port your Go app listens on
